-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: May 30, 2013 at 10:19 AM
-- Server version: 5.1.41
-- PHP Version: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `pcm`
--

-- --------------------------------------------------------

--
-- Table structure for table `document`
--

CREATE TABLE IF NOT EXISTS `document` (
  `documentID` int(11) NOT NULL AUTO_INCREMENT,
  `documentTitle` varchar(255) NOT NULL,
  `documentAuthor` varchar(255) NOT NULL,
  `documentKeywords` varchar(255) NOT NULL,
  `documentDescription` varchar(255) NOT NULL,
  `documentContent` varchar(255) NOT NULL,
  `documentIdName` varchar(50) NOT NULL,
  PRIMARY KEY (`documentID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=32 ;

--
-- Dumping data for table `document`
--

INSERT INTO `document` (`documentID`, `documentTitle`, `documentAuthor`, `documentKeywords`, `documentDescription`, `documentContent`, `documentIdName`) VALUES
(1, 'Research, Literature and Academia', 'Appold, Barbara E., M.Ed.', 'Articles, books, conference presentations, academic research, institutions of higher education.', 'Dr. Kahler''s work has been the subject of ARTICLES, BOOKS, CONFERENCE PRESENTATIONS and ACADEMIC RESEARCH. In addition, his work has been taught at many INSTITUTIONS OF HIGHER EDUCATION. These are described, and in the case of certain research studies and', 'Dr. Kahler''s work has been the subject of ARTICLES, BOOKS, CONFERENCE PRESENTATIONS and ACADEMIC RESEARCH. In addition, his work has been taught at many INSTITUTIONS OF HIGHER EDUCATION. These are described, and in the case of certain research studies and', 'research-and-publication-academia-button-1'),
(2, 'Leaderships, Group Dynamics & Personality', 'Jean-Pierre Raffalli', '', 'This article explores the concept of team leadership. Its purpose is to study how a leader can use his internal resources or "talents" to deal with group dynamics for which I will use the perspective of the Process Communication Model (Kahler, 1979), a re', 'Introduction\r\nThe topic of leadership spans a wealth of knowledge that has grown exponentially in the past decades. Early approaches to leadership focused on the personality traits and, later on the activities of the leader. More recent research has dealt', 'research-and-publication-articles-button-1'),
(3, 'This Strange Dominant Logic, Decoding Behaviour Under Stress', 'Elyssebeth Leigh, Werner Naef; Andrea Naef, Russell Blakelock', '', 'Simulation enables rehearsal of human actions before actors move into ''real time''. It allows for long term\r\nplanning and/or immediate events - to devise appropriate responses ahead of time. Since those earliest known\r\nsimulations the behaviour of the indi', '1. INTRODUCTION\r\nRehearsal is essential for actors preparing to take part\r\nin any theatrical activity. Simulation has a theatrical\r\nbase, in that it similarly is a time for rehearsing – not\r\nof fiction – but of future reality. Individuals preparing\r\nto en', 'research-and-publication-articles-button-2'),
(4, 'New Zealand Health & Hospital', 'New Zealand Health & Hospital', '', 'The Series and Sentinel Events list published\r\nrecently by the Ministry of Health''s Quality\r\nImprovement Committee, which reported 258\r\nincidents, including 76 deaths, is alarming but\r\nit simply highlights the stressful environment of\r\nhospitals in this c', '“Human Error is a major contributing factor for most of these incidents.\r\nThey occur when individuals are under pressure or stress. In these\r\nsituations, training sometimes goes out the window as a strange dominant\r\nlogic takes over, and professional peop', 'research-and-publication-articles-button-3'),
(5, 'Learning Process Model and Techniques for Safety Education, Training, Teaching', 'Werner Naef', '', 'This paper presents the findings of clinical research focusing on behaviour, communication, motivation and\r\nconflict solving. Put into occupational life the outcomes of this research allow for early identification of\r\nwarning signals indicating that someo', '2.1 Are you familiar with behaviours such as these?\r\nA supervisor attacking staff for not doing things the way they were told? For not thinking clearly, for\r\nbeing ''stupid''? ''Why the hell do you not understand how this should be done? Can’t you think?''\r\n', 'research-and-publication-articles-button-4'),
(6, 'Articles', 'Kahler Communications Oceania', '', 'Leigh, Elyssebeth, Blakelock, Russell, Naef, Werner and Naef, Andrea, "This Strange Dominant Logic, Decoding Behaviour under Stress", SIMTECT 2009 Conference Paper - winner of the "Best Paper Award". Download PDF\r\nNaef, Werner, "Hospital incidents report', 'Leigh, Elyssebeth, Blakelock, Russell, Naef, Werner and Naef, Andrea, "This Strange Dominant Logic, Decoding Behaviour under Stress", SIMTECT 2009 Conference Paper - winner of the "Best Paper Award". Download PDF\r\nNaef, Werner, "Hospital incidents report', 'research-and-publication-articles-button-5'),
(7, 'The Process Model: Personality Types, miniscripts, and Adaptations', 'Taibi Kahler', '', 'The author chronicles his Process Model\r\nfrom the miniscript to his research‐based\r\nsix Personality Types. Paul Ware''s "Doors"\r\nare expanded into six perceptions, and his\r\nAdaptations are identified in miniscript\r\nbehaviors of three degrees of distress, i', 'My interest in process began by concentrating\r\non functional analysis and discovering\r\nDrivers (1969‐1971). As they were defined\r\nand described as functional counterscripts,\r\nthey were observable by words, tones, gestures,\r\nposture, and facial expressions', 'research-and-publication-articles-button-6'),
(8, 'Myers Briggs / Personality Pattern Inventory', 'Terry McGuire, Taibi Kahler, Pat Stansbury', '', 'Determine if there is an algorithm that will demonstrate a predictable personality description from the output of either of two different personality survey instruments (Myers-Briggs Type Indicator (TM) and the Personality Pattern Inventory (TM)).', 'Determine if there is an algorithm that will demonstrate a predictable personality description from the output of either of two different personality survey instruments (Myers-Briggs Type Indicator (TM) and the Personality Pattern Inventory (TM)).', 'research-and-publication-validation-button-1'),
(9, 'Astronauts; Reflections on Current Selection Methodology, Astronaut Personality, and the Space Station', 'Terence F. McGuire', '', 'Astronauts; Reflections on Current Selection Methodology, Astronaut Personality, and the Space Station', 'Astronauts; Reflections on Current Selection Methodology, Astronaut Personality, and the Space Station', 'research-and-publication-validation-button-2'),
(10, 'Personality Pattern Inventory Validity Studies', 'Taibi Kahler', '', 'The Personality Pattern Inventory (PPI) has its foundations in behavioral psychology, and\r\nwas originally designed to identify positive and negative characteristics of individuals\r\n(1972).\r\nOf major importance to this Process Communication Model (PCM) is', 'PERSONALITY PATTERN INVENTORY\r\nVALIDATION STUDIES\r\nAs the Personality Pattern Inventory (PPI) was first conceived, the following five\r\nelements germane to the experimental design construction were considered:\r\n1. That a set of questions is administered to', 'research-and-publication-validation-button-3'),
(11, 'Report of adherence to theory discovered when the personality pattern inventory (tm) was administered to subjects twice.', 'Kahler Communications Inc', '', 'The study was commissioned by Kahler Communications Inc, Little Rock, AR for the purpose of reviewing what support, if any, there was to be found of Dr. Kahler''s theory with respect to Phase progression/regression/statics and, additionally, examine the co', 'The study was commissioned by Kahler Communications Inc, Little Rock, AR for the purpose of reviewing what support, if any, there was to be found of Dr. Kahler''s theory with respect to Phase progression/regression/statics and, additionally, examine the co', 'research-and-publication-validation-button-4'),
(12, 'How to replicate Performance?', 'Sandy Pentland', '', 'Sandy Pentland, director at Boston MIT''s Human Dynamics\r\nLaboratory and his team looked into reasons for varying\r\nteam performance. We all know high performing individuals\r\nand teams means higher revenue, more successfully completed\r\nprojects, motivated s', 'Research also shows that the most important, complex,\r\ndelicate interactions happen face to face or sometimes over\r\nthe phone.\r\nMost organisations don’t know how to measure the effectiveness\r\nof these interactions, which means they have no\r\nunderstanding ', 'what-is-pcm-general-button-1'),
(13, 'History of PCM and PTM', 'Kahler Communications Oceania', '', '', 'In the early 1970s, Dr. Kahler, then at Purdue University, made a series of remarkable discoveries. He observed that there was a process involved in verbal communication – identifiable sequences by which people interacted with one another in both positive', 'what-is-pcm-general-button-2'),
(14, 'PCM email flyer', 'Kahler Communications Oceania / Sandy Petland', '', 'We all know high performing individuals and teams mean greater\r\nmotivation, increased productivity and higher revenue.\r\nIt also leads to reduced failure or accident rates, less sick days\r\nand reduced staff turnover.\r\nSandy Pentland, director at Boston MIT', 'He says: "If you just look at patterns of communications - together with the body\r\nlanguage - you can account for 50% of the variation between poorly performing\r\nteams and highly performing groups. 50% might not sound like much but what that\r\nmeans is tha', 'what-is-pcm-general-button-3'),
(15, 'What is PCM? - Videos', '', '', 'Following videos:\r\nhttp://www.youtube.com/watch?v=p-DxcZudvWQ\r\n(Spencer, Shenk, Capers & Associates, Inc. / USA)\r\n\r\nhttp://www.youtube.com/watch?v=ICLzqIexSTI\r\n(English, Kahler Communication Germany)\r\n\r\nhttp://www.youtube.com/watch?v=CrazcX6hSAA\r\n(French,', 'Following videos:\r\nhttp://www.youtube.com/watch?v=p-DxcZudvWQ\r\n(Spencer, Shenk, Capers & Associates, Inc. / USA)\r\n\r\nhttp://www.youtube.com/watch?v=ICLzqIexSTI\r\n(English, Kahler Communication Germany)\r\n\r\nhttp://www.youtube.com/watch?v=CrazcX6hSAA\r\n(French,', 'what-is-pcm-general-button-4'),
(16, 'What is PCM?', 'Andrea Naef', '', 'Like so many others, I strive to live a happy and fulfilled life\r\n and there are times when I think I''m doing quite a good\r\njob! And sometimes my days are filled with stressed out\r\nclients, family members and friends who don’t understand\r\nor are demandin', 'Like so many others, I strive to live a happy and fulfilled life\r\n and there are times when I think I''m doing quite a good\r\njob! And sometimes my days are filled with stressed out\r\nclients, family members and friends who don’t understand\r\nor are demandin', 'what-is-pcm-general-button-5'),
(17, 'If you want them to listen, talk their language', 'Elisabeth Feuersenger and Andrea Naef', '', 'Communication, Motivation and Success in Business and Personal Relationships using the Process Communication Model.', 'Communication, Motivation and Success in Business and Personal Relationships using the Process Communication Model.', 'what-is-pcm-type-button-1'),
(18, 'Type Explanations', 'Kahler Washington', '', 'http://www.youtube.com/watch?v=OricVhRVz9I\r\n(Kahler Washington, Reactor)\r\n\r\nhttp://www.youtube.com/watch?v=LLUp7YTdeJo\r\n(Kahler Washington - Workaholic)\r\n\r\nhttp://www.youtube.com/watch?v=YpGsLlrj9Ro\r\n(Kahler Washington – Rebel)\r\n\r\nhttp://www.youtube.com/', 'http://www.youtube.com/watch?v=OricVhRVz9I\r\n(Kahler Washington, Reactor)\r\n\r\nhttp://www.youtube.com/watch?v=LLUp7YTdeJo\r\n(Kahler Washington, Workaholic)\r\n\r\nhttp://www.youtube.com/watch?v=YpGsLlrj9Ro\r\n(Kahler Washington, Rebel)\r\n\r\nhttp://www.youtube.com/', 'what-is-pcm-type-button-2'),
(19, 'Attracting Students to STEM Careers', 'Judith Pauley', '', 'Science and technology are increasingly important in our daily lives, in the economic survival of our country and in maintaining our standard of living. Many leaders are concerned about ways to attract more students—especially female students—to pursue ca', 'The recently released 2009 National Assessment of Educational Progress (NAEP) report—which covers grades 4, 8 and 12—stated that fewer than a third of students have a solid grasp of science and fewer than 3% scored in the advanced level.1 A few weeks earl', 'where-is-pcm-education-button-1'),
(20, 'Establishing Relationships to Reduce Bullying', 'Joe and Judith Ann Pauley', '', 'Bullying is a major problem in most schools today, and students, parents,\r\neducators and the government are concerned. Many people and organizations, including\r\nthe U.S. government, are determined to do something about it. The courts have held\r\nschools an', 'Definition of bullying\r\nAccording to the research, there are four types of bullying: verbal bullying,\r\nspreading rumors, physical bullying and cyber bullying. Texting bullying is becoming\r\nespecially prevalent in many schools. While researchers have found', 'where-is-pcm-education-button-2'),
(21, 'QED News', 'ASQ (American Society for Quality)', '', 'Mission\r\nStatement\r\nTo facilitate the\r\nidentification,\r\ncommunication, and\r\npromotion of the use of\r\nquality principles,\r\nconcepts, and\r\ntechnologies for\r\ncontinuous\r\nimprovement in all\r\naspects of education.', 'A Message From the\r\nDivision Chair\r\nby John Dew\r\nChair, Education Division\r\nWhat have you been reading this\r\nsummer? I''ve certainly enjoyed reading\r\nsome of the current best sellers\r\nlike Freakonomics, but some of my\r\nbest reading has come from the dusty\r', 'where-is-pcm-education-button-3'),
(22, 'Meeting Students’ Needs: The Key to Dropout Prevention', 'Dianne F. Bradley, Judith Ann Pauley and Joseph F. Pauley', '', '', 'The U.S. Department of Education reports that 51\r\npercent of school dropouts said they did not like school\r\nbecause they felt as if they did not belong. 35 percent said\r\nthey could not get along with their teachers, this increased\r\nto 51 percent when cons', 'where-is-pcm-education-button-4'),
(23, 'Establishing Relationships to reduce bullying and increase student achievement', 'Judith Ann Pauley, Joseph F. Pauley', '', 'Educators have used the research-based concepts of Process Communication very effectively to reduce\r\nbullying and other student negative behaviors and to improve the motivation and academic achievement of\r\nevery student. Participants will learn the concep', 'Introduction\r\nAs every teacher knows, bullying is a major problem in most schools today. Moreover, the advent of the\r\ninternet has provided additional means for students to bully others. Frequently cyberspace bullying is meaner\r\nand more degrading than th', 'where-is-pcm-education-button-5'),
(24, 'Why educators have problems with some students', 'Michael B. Gilbert', 'Communications, Learning styles, Students', 'Some educators believe that if they do their jobs properly, all their students will learn,\r\nand school will be a happy, productive and comfortable place for everybody. The reality is that not\r\neveryone has the same preferences ± for teaching and learning.', 'Introduction\r\nPeople who become professional educators see their futures in terms of helping\r\nothers, structuring logical learning sequences and environments, and offering\r\nthe citizens of tomorrow things which are valuable and important. They see\r\ntheir ', 'where-is-pcm-education-button-6'),
(25, 'Learning Styles and Student Achievement', 'National Dropout Prevention Center/Network', '', 'The focus of this issue is learning styles - preferred ways of understanding, thinking, and processing information. This is one of the 15 effective strategies the national dropout prevention center recommends to reduce the number of dropouts. There are se', 'Unfortunately, this is not done\r\nin most classrooms. Michael\r\nGilbert''s research and that of\r\nthe editors have demonstrated that\r\nmost educators teach the way they\r\nwere taught or the way they would\r\nprefer to be taught. Gilbert also\r\ndiscovered that 90% ', 'where-is-pcm-education-button-7'),
(26, 'Better communication will improve healthcare', 'Elizabeth Wood', '', 'Health Matters is a fortnightly column contributed by Nelson medical professionals and advocates. Today, Elizabeth Wood considers the importance of good communication.', 'Health Matters is a fortnightly column contributed by Nelson medical professionals and advocates. Today, Elizabeth Wood considers the importance of good communication.', 'where-is-pcm-health-button-1'),
(27, 'PCM in medicine / healthcare', 'Kahler Washington', '', 'http://www.youtube.com/watch?v=wwr9JLN5afk\r\n(Kahler Washington - PCM in medicine)', 'http://www.youtube.com/watch?v=wwr9JLN5afk\r\n(Kahler Washington - PCM in medicine)', 'where-is-pcm-health-button-2'),
(28, 'Wellness: A Professional Obligation', 'Marion Andrew', '', 'Anaesthetics make critical decisions when patients are at some of the most vulnerable times in their lives, writes Dr Marion Andrew (FANZCA).', 'Anaesthetics make critical decisions when patients are at some of the most vulnerable times in their lives, writes Dr Marion Andrew (FANZCA).', 'where-is-pcm-health-button-3'),
(29, 'Kahler organisation links', 'Kahler Communications Inc', '', 'Kahler organisation links', 'Kahler organisation links', 'where-is-pcm-organisations-button-1'),
(30, 'Establishing relationships: The key to maintaining quality teams', 'Judith Ann Pauley, Joseph F. Pauley', 'Behavior, communication, distress, Gallup, interaction style, management,\r\nmanagement style, mismanagement, motivation, personality, personality type, process\r\ncommunication, psychological needs, quality, relationships, Taibi Kahler.', 'Research shows that all employees can do well on teams and in the workplace if\r\nthey are managed and motivated according to their needs (Bradley, Pauley & Pauley,\r\n2006). Dr. Taibi Kahler, an internationally acclaimed psychologist, has shown that the\r\nkey', 'Text\r\nDr. Taibi Kahler, an internationally acclaimed clinical psychologist, has shown\r\nthat the key to forming positive relationships with employees and fellow team members\r\nis to help them get their motivational needs met positively and use an Individual', 'where-is-pcm-management-button-1'),
(31, 'Leadership, Group Dynamics & Personality', 'Jean-Pierre Raffalli', '', 'This article explores the concept of team leadership. Its purpose is to study how a leader can use his internal resources or "talents" to deal with group dynamics for which I will use the perspective of the Process Communication Model (Kahler, 1979), a re', 'Introduction\r\nThe topic of leadership spans a wealth of knowledge that has grown exponentially in the past decades. Early approaches to leadership focused on the personality traits and, later on the activities of the leader. More recent research has dealt', 'where-is-pcm-management-button-2');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
